version: "3.8"

services:
  app:
    build: .
    image: nodeapp
    container_name: nodeapp
    ports:
      - 90:8080
    environment:
      - DB_USERNAME=reading_list_app
      - DB_PASSWORD=password
      - DB_DATABASE=reading_list
      - DB_HOST=postgres
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      - pgnodeapp
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
    command: ["./wait-for", "db:5432", "--", "npm", "run", "build-start"]
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=reading_list_app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reading_list
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      pgnodeapp:
        aliases:
          - postgres

volumes:
  postgres-db:
networks:
  pgnodeapp:
    driver: bridge
