version: "3.8"

services:
  api:
    build: ./
    image: flaskapp
    container_name: flask-api
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=book_ratings.py
      - DATABASE_URL=postgresql://ratings_user:password@db/ratings
    volumes:
      - .:/app
    networks:
      - flaskapp
    depends_on:
      - db
    entrypoint: /app/entrypoint.sh
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=ratings_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ratings
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      flaskapp:

volumes:
  postgres-db:
networks:
  flaskapp:
    driver: bridge
